### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [Faldang/GOGWishlistExport#1]
Hi. What license applies to your wishlist export script? As it is now, I do not see any license info, which means it is "all rights reserved", and as I understand it that means nobody is allowed to legally use it :(

If it has a permissive license (e.g. MIT), I will be very happy to contribute any new "features" that I can then legally add, back to you via Pull Requests.

**Comment by Faldang** [comment]
Hi :)

I haven't done much development so I hadn't really considered a license for this. I've now added the license file with the GPL.

Will that work for you? :)
